[package]
name = "webdev-book"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.36", features = ["full"] }
warp = "0.3.6"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.113"
log = "0.4.20"
log4rs = "1.3.0"
uuid = { version = "1.7.0", features = ["v4"] }