version: "1.0"

volumes:
  db_data:

networks:
  db_net:

services:
  db:
    build: db
    environment:
      POSTGRES_DB: webdev_book
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_net
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
