[alias]
docs = "doc --no-deps"

[env]
RUST_LOG = "webdev_book=info,warp=error"
API_LAYER_KEY = "KHFM68sNbwzuPqELmjnevUv2k17EdiBE"
DATABASE_URL = "postgres://admin:admin@localhost:5432/webdev_book"
X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR = "C:\\Program Files\\OpenSSL-Win64"
X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR = "C:\\Program Files\\OpenSSL-Win64\\lib\\VC\\x64\\MD"
