[alias]
docs = "doc --no-deps"

[env]
X86_64_PC_WINDOWS_MSVC_OPENSSL_DIR = "C:\\Program Files\\OpenSSL-Win64"
X86_64_PC_WINDOWS_MSVC_OPENSSL_LIB_DIR = "C:\\Program Files\\OpenSSL-Win64\\lib\\VC\\x64\\MD"
